Repository Hyperfoil/Horreum, pull requests merged in 2023-10, with the labels that each got.

#694 Use panache .count() function for RunService.listBySchema() to ensure…
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
Labels: enhancement, master

#670 Migration to React 18
  horreum-backend/src/main/resources/application.properties
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/store.ts
Labels: feature

#735 fixes #733
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TableReportMapper.java
Labels: bug

#738 Fix login issue with keycloack in dev mode with prod backup
  horreum-backend/src/main/resources/application.properties
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
Labels: bug, master, developer

#741 node: Version 18.18.1 Hydrogen (LTS)
  horreum-backend/src/main/resources/application.properties
Labels: enhancement, 0.9.x

#747 remove javax dependency
  horreum-ui/pom.xml
Labels: enhancement, master

#753 Use specific `cmd` to install dependencies by quinoa
  horreum-backend/src/main/resources/application.properties
Labels: enhancement

#764 Fix dev services on podman, plus tesing enhancements
  horreum-backend/pom.xml
  horreum-integration-tests/pom.xml
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/config/HorreumDevServicesKeycloakConfig.java
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/config/HorreumDevServicesPostgresConfig.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/Const.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
  pom.xml
Labels: bug, enhancement, master, developer

#769 Fix missing views in datasets table - Fixes #767
  horreum-web/src/domain/runs/TestDatasets.tsx
Labels: bug

#790 include status badge of CI
  README.md
Labels: enhancement

#828 Config: package install automatically detect by quinoa
  horreum-backend/src/main/resources/application.properties
Labels: enhancement

#834 Fix mapping issue in change detection variable definitions: fixes #822
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/Variable.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/VariableMapper.java
Labels: bug, enhancement

#835 Fix dev services with PROD backup
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
Labels: bug

#830 fixes #811
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/RunDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
Labels: bug

#849 Modify default Access for new label: fixes #844
  horreum-web/src/domain/schemas/Labels.tsx
Labels: bug
