Repository Hyperfoil/Horreum, pull requests merged in 2023-11, with the labels that each got.

#864 Define sequences and ID generators for each PeristentLog subclasses: …
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/ActionLogDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/PersistentLogDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/alerting/DatasetLogDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/alerting/TransformationLogDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/report/ReportLogDAO.java
  horreum-backend/src/main/resources/db/changeLog.xml
Labels: backend, 0.10.x

#876 Combine: owner and access columns, fixes #404 #405 #428 #430
  horreum-web/src/components/AccessIconOnly.tsx
  horreum-web/src/domain/runs/TestDatasets.tsx
  horreum-web/src/domain/runs/TestRuns.tsx
  horreum-web/src/domain/schemas/AllSchema.tsx
  horreum-web/src/domain/tests/AllTests.tsx
Labels: enhancement

#827 fix: KeycloakInstance deprecated
  horreum-web/src/auth.tsx
  horreum-web/src/keycloak.ts
Labels: enhancement

#879 Use `@quarkus 3.5.1`
  pom.xml
Labels: enhancement, master

#896 dowgrade min JDK version for horreum-infra-common
  infra/horreum-infra-common/pom.xml
Labels: bug

#909 Correctly render dataset filters - Fixes #908
  horreum-web/src/domain/runs/TestDatasets.tsx
Labels: bug, UI

#912 correct config for keycloak admin client in dev mode : Fixes #911
  horreum-backend/src/main/resources/application.properties
Labels: bug, developer

#858 Node: Latest LTS Version: 20.9.0
  horreum-backend/src/main/resources/application.properties
Labels: enhancement

#904 Add hover effect on nav elements, fixes #826
  horreum-web/src/App.tsx
Labels: feature

#918 Do not filter report config if report is not peristed: Fixes #877
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ReportComponentMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TableReportMapper.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
Labels: bug

#920 Do not filter report config if report is not peristed: Fixes #877
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ReportComponentMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TableReportMapper.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
Labels: bug, stable

#921 Run GH workflows against all branches
  .github/workflows/main.yml
Labels: enhancement

#925 Null ID for schema if id less than : Fixes #924
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
Labels: bug, master

#926 Null ID for schema if id less than : Fixes #924
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
Labels: bug, stable

#933 Correct experiment datatypes in UI. Retrun experiment results in prod mode
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExperimentComparison.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/ExperimentComparisonDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
  horreum-web/src/domain/tests/Experiments.tsx
Labels: bug, stable

#934 Correct experiment datatypes in UI. Retrun experiment results in prod mode
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExperimentComparison.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/ExperimentComparisonDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
  horreum-web/src/domain/tests/Experiments.tsx
Labels: bug, stable

#935 Automatically copy generated openapi.yaml to docs/site - Fixes #932
  pom.xml
Labels: documentation, enhancement

#940 Do not assume fingerprint values are all strings: Fixes #938
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValue.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValues.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/FingerprintValue.java
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
  horreum-web/src/domain/alerting/Changes.tsx
Labels: bug, master

#941 Do not assume fingerprint values are all strings: Fixes #938
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValue.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValues.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/FingerprintValue.java
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
  horreum-web/src/domain/alerting/Changes.tsx
Labels: bug, stable

#939 Upgrade `@Quarkus 3.5.3`
  pom.xml
Labels: enhancement, master

#942 Bump postgres to version 16
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
  pom.xml
Labels: bug, master, backend

#943 Bump postgres to version 16
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
  pom.xml
Labels: bug, stable, backend

#946 Lookup testID with DatasetID by schema: Fixes #917
  docs/site/content/en/openapi/openapi.yaml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/resources/application.properties
Labels: bug, master

#947 Lookup testID with DatasetID by schema: Fixes #917
  docs/site/content/en/openapi/openapi.yaml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/resources/application.properties
Labels: bug, stable, backend

#936 Setup SSL encryption with postgres test container
  horreum-backend/src/main/resources/application.properties
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/config/HorreumDevServicesPostgresConfig.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/Const.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Labels: enhancement, master, developer

#948 Check if dev services backup directory exists and is not empty
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Labels: bug, stable, developer

#952 Correctly query for looking up watches: Fixes #950
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
Labels: bug, master

#958 Add permissions check on PG dump directory and helpful error message.
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Labels: enhancement

#959 Bump javadoc
  pom.xml
Labels: enhancement

#963 Lookup fingerprints by hash in database : Fixes #962
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
  horreum-backend/src/main/resources/db/changeLog.xml
Labels: enhancement, high, 0.10.x, 0.11.x
