Repository Hyperfoil/Horreum, pull requests merged in 2023-03, with the labels that each got.

#407 added openapi annotation for the response of RunService.addRunFromData
  horreum-model/src/main/java/io/hyperfoil/tools/horreum/api/RunService.java
Labels: enhancement, master, stable

#410 Install backend jar into local repo. Needed for Integration tests and…
  horreum-backend/pom.xml
Labels: bug, master, stable

#412 update: quinoa version 1.2.4 to 1.2.5
  pom.xml
Labels: enhancement, master, stable

#457 Correct issues with infra startup scripts running in bridged mode
  infra/app-init.sh
  infra/docker-compose.yml
Labels: bug
