Repository Hyperfoil/Horreum, pull requests merged in 2023-06, with the labels that each got.

#543 re-build keycloak container image in infra as root
  infra/Dockerfile.keycloak
Labels: bug, master, stable

#549 Add ConfigService to horreum client
  horreum-client/src/main/java/io/hyperfoil/tools/HorreumClient.java
Labels: bug, master, stable

#554 Add ConfigService to horreum client
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
Labels: bug, master

#559 destructure TableReportConfigPage.tsx props
  webapp/src/domain/reports/TableReportConfigPage.tsx
Labels: enhancement

#569 Fix mapper for Runs and Notifications settings. Fixes #537
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/NotificationSettingsMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/RunMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/NotificationServiceImpl.java
Labels: bug

#576 Fix new test import for a Horreum instance that does not have test de…
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/ExperimentComparison.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
Labels: bug

#579 Destructure component of alerting
  webapp/src/domain/alerting/PanelChart.tsx
  webapp/src/domain/alerting/RecalculateModal.tsx
Labels: enhancement
