Repository Hyperfoil/Horreum, pull requests merged in 2023-12, with the labels that each got.

#961 Support Docker Desktop for building native executables with quarkus 3.6.0
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
  horreum-backend/pom.xml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
  pom.xml
Labels: enhancement, master

#966 Upgrade: latest LTS node v20.10.0 and npm 10.2.3
  horreum-backend/src/main/resources/application.properties
Labels: enhancement, master

#968 CI: depreciated github action
  .github/workflows/main.yml
Labels: enhancement, master

#978 Use latest version of quinoa 2.3.0
  pom.xml
Labels: enhancement, master

#980 Revert "Add permissions check on PG dump directory and helpful error message."
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Labels: bug, developer

#981 Revert "Add permissions check on PG dump directory and helpful error message."
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Labels: bug, developer

#985 Fix directory checks for backup db, where container has changed perms…
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Labels: bug, master, developer

#986 Fix directory checks for backup db, where container has changed perms…
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/PostgresResource.java
Labels: bug, stable, developer

#989 Correctly handle JSON types in DB query in SchemaServiceImpl.findUsages()
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
Labels: bug, master

#990 Correctly handle JSON types in DB query in SchemaServiceImpl.findUsages()
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ReportServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
Labels: bug, stable, backend

#994 NPE: Retransform Datasets
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ValidationError.java
Labels: bug

#1000 update run_schemas table, prevent js bug from crashing UI, correctly cast metadata
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
  horreum-web/src/domain/reports/TableReportView.tsx
Labels: bug, master

#1001 update run_schemas table, prevent js bug from crashing UI, correctly cast metadata.
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
  horreum-web/src/domain/reports/TableReportView.tsx
Labels: bug, stable
