Repository Hyperfoil/Horreum, pull requests merged in 2024-04, with the labels that each got.

#1572 Fix ChangeDetection additions.
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
Labels: area/backend, backport

#1526 Bump to actions/upload-artifact@v4
  .github/workflows/main.yml
Labels: type/enhancement

#1581 MPL-68: make run_schemas updates asynchronous
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/bus/AsyncEventChannels.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
  horreum-web/src/Banner.tsx
  horreum-web/src/domain/schemas/Schema.tsx
Labels: area/backend, backport

#1585 Execute TEST_NEW actions with the test id
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
Labels: backport

#1489 Ignore reformat files/folder
  horreum-web/src/.prettierignore
Labels: area/UI, backport, area/integration

#1591 Remove unused object from vite.config.ts
  horreum-web/vite.config.ts
Labels: type/enhancement, area/UI

#1612 Fix SecurityMigration realm
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/KeycloakUserServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/KeycloakTestProfile.java
Labels: backport

#1600 Improve SchemaServiceImpl testing
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
Labels: backport

#1624 Fix javadoc linting error
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
Labels: backport

#1620 CI: check for uncommitted changes
  .github/workflows/main.yml
Labels: backport
