Repository Hyperfoil/Horreum, pull requests merged in 2024-05, with the labels that each got.

#1648 Fix base image for release
  horreum-backend/src/main/docker/Dockerfile.jvm.base
Labels: backport

#1656 Setup unit testing bypassing REST
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceNoRestTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceNoRestTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
Labels: type/enhancement, area/backend, backport

#1672 Correct User ID in base image: Fixes #1669
  horreum-backend/src/main/docker/Dockerfile.jvm.base
Labels: backport

#1681 Fix reports nav links
  horreum-web/src/domain/reports/ListReportsModal.tsx
  horreum-web/src/domain/schemas/FindUsagesModal.tsx
Labels: backport

#1689 Validate test/schema import format: Fixes #1685
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
  horreum-backend/src/main/resources/META-INF/beans.xml
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceNoRestTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceNoRestTest.java
Labels: backport

#1697 Reinstate schema import, remove unneccesary components. Fixes: #1676
  horreum-web/src/components/ExportImport.tsx
  horreum-web/src/components/ImportButton.tsx
  horreum-web/src/components/SavedTabs.tsx
  horreum-web/src/domain/admin/Admin.tsx
  horreum-web/src/domain/schemas/Schema.tsx
  horreum-web/src/domain/schemas/SchemaExportImport.tsx
  horreum-web/src/domain/schemas/SchemaImportButton.tsx
  horreum-web/src/domain/schemas/SchemaList.tsx
  horreum-web/src/domain/tests/AllTests.tsx
  horreum-web/src/domain/tests/Test.tsx
  horreum-web/src/domain/tests/TestExportImport.tsx
  horreum-web/src/domain/tests/TestImportButton.tsx
  horreum-web/src/domain/tests/TestSettings.tsx
  horreum-web/src/domain/user/UserSettings.tsx
Labels: backport

#1660 Intercept JPAIdentityProvider to set the required roles
  horreum-backend/pom.xml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/JpaIdentityProviderRolesExtension.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BasicAuthTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/DatabaseRolesTestProfile.java
Labels: backport

#1713 Clear CI disk space before running tests. Fixes #1712
  .github/scripts/ci-prerequisites.sh
  .github/workflows/main.yml
Labels: backport

#1707 Sanitize folder before adding it as url query param
  horreum-web/src/domain/tests/AllTests.tsx
Labels: backport

#1717 Reinstate errorElement for main route. Fixes #1716
  horreum-web/src/App.tsx
Labels: backport

#1725 Only initialize graal JS context when required. Fixes #1723
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
Labels: backport

#1709 Use `Link` instead `NavLink` to navigate 404
  horreum-web/src/404.tsx
Labels: type/enhancement, area/UI

#1720 Refactor test settings and access rights
  horreum-web/src/components/ConfirmDeleteModal.tsx
  horreum-web/src/components/SplitForm.tsx
  horreum-web/src/domain/tests/Access.tsx
  horreum-web/src/domain/tests/Test.tsx
  horreum-web/src/domain/tests/TestSettings.tsx
  horreum-web/src/domain/tests/Tokens.tsx
Labels: backport

#1748 Enable pg_stat_statements in postgres for dev mode: Fixes #1747
  infra/horreum-infra-common/src/main/resources/postgres.config.properties
Labels: backport
