Repository Hyperfoil/Horreum, pull requests merged in 2024-02, with the labels that each got.

#1233 Remove 'history' from redux store.ts: Fixes #1232
  horreum-web/package-lock.json
  horreum-web/package.json
  horreum-web/src/alerts.tsx
  horreum-web/src/api.tsx
  horreum-web/src/auth.tsx
  horreum-web/src/keycloak.ts
  horreum-web/src/store.ts
Labels: type/enhancement, branch/master, area/UI, area/dependency, backport

#1238 remove unnecessary dependencies: Fixes #1237
  horreum-backend/pom.xml
Labels: type/bug, backport, area/build

#1239 [0.11.x] remove unnecessary dependencies: Fixes #1237
  horreum-backend/pom.xml
Labels: type/bug, branch/0.11.x, area/build

#1240 [0.11.x] Bump redux-thunk from 2.4.1 to 2.4.2 in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, branch/0.11.x, area/dependency

#1224 Fix conflicting npm dependencies and bump typescript 4 to 5
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, area/dependency, backport

#1234 [0.11.x] Remove 'history' from redux store.ts: Fixes #1232
  horreum-web/package-lock.json
  horreum-web/src/alerts.tsx
  horreum-web/src/api.tsx
  horreum-web/src/auth.tsx
  horreum-web/src/keycloak.ts
  horreum-web/src/store.ts
Labels: type/enhancement, area/UI, branch/0.11.x, area/dependency

#1241 [0.11.x] Fix conflicting npm dependencies and bump typescript 4 to 5
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/0.11.x, area/dependency

#1183 Add endpoint to fetch the roles of an authenticated user: Fixes #1187
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
  horreum-backend/pom.xml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
  horreum-backend/src/main/resources/application.properties
  horreum-web/src/Login.tsx
  horreum-web/src/api.tsx
  horreum-web/src/keycloak.ts
Labels: type/feature, branch/master, area/UI, area/backend

#1249 Run CI for stable branch with each push
  .github/workflows/main.yml
  docs/RELEASE.md
Labels: type/enhancement, branch/master, area/build

#1250 Revert "Add endpoint to fetch the roles of an authenticated user: Fixes #1187"
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
  horreum-backend/pom.xml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
  horreum-backend/src/main/resources/application.properties
  horreum-web/src/Login.tsx
  horreum-web/src/api.tsx
  horreum-web/src/keycloak.ts
Labels: type/bug, branch/master, area/UI

#1251 [0.11.x] Bump clsx from 1.2.1 to 2.1.0 in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: type/enhancement, area/UI, area/dependency

#1252 [0.11.x] Bump monaco-editor from 0.36.1 to 0.45.0 in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, branch/0.11.x, area/dependency

#1229 Multi-index queries for ElasticSearch Integration: Fixes #1207
  docs/site/content/en/docs/Tutorials/query-elasticserach/index.md
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
  horreum-backend/src/test/resources/data/config-quickstart.jvm.json
  horreum-backend/src/test/resources/data/experiment-ds1.json
  horreum-backend/src/test/resources/data/experiment-ds2.json
  horreum-backend/src/test/resources/data/experiment-ds3.json
  horreum-backend/src/test/resources/data/experiment-elastic.json
  horreum-backend/src/test/resources/data/experiment-meta-data-d1.json
  horreum-backend/src/test/resources/data/experiment-meta-data-d2.json
  horreum-backend/src/test/resources/data/experiment-meta-data-d3.json
Labels: type/feature, area/backend, priority/high, backport

#1253 [0.11.x] Multi-index queries for ElasticSearch Integration: Fixes #1207
  docs/site/content/en/docs/Tutorials/query-elasticserach/index.md
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
  horreum-backend/src/test/resources/data/config-quickstart.jvm.json
  horreum-backend/src/test/resources/data/experiment-ds1.json
  horreum-backend/src/test/resources/data/experiment-ds2.json
  horreum-backend/src/test/resources/data/experiment-ds3.json
  horreum-backend/src/test/resources/data/experiment-elastic.json
  horreum-backend/src/test/resources/data/experiment-meta-data-d1.json
  horreum-backend/src/test/resources/data/experiment-meta-data-d2.json
  horreum-backend/src/test/resources/data/experiment-meta-data-d3.json
Labels: type/enhancement, area/UI, area/backend, branch/0.11.x

#1262 Add endpoint to fetch the roles of an authenticated user ; Fixes #1246
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/UserService.java
  horreum-backend/pom.xml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
  horreum-backend/src/main/resources/application.properties
  horreum-web/src/Login.tsx
  horreum-web/src/api.tsx
  horreum-web/src/auth.tsx
  horreum-web/src/keycloak.ts
Labels: type/feature, branch/master, area/UI, area/backend, backport

#1264 Always fetch roles from backend : Fixes #1255
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
  horreum-web/src/keycloak.ts
Labels: type/enhancement, branch/master, area/UI

#1270 Re-commit package-lock.json with the correct spacing. Fixes #1269
  docs/site/content/en/openapi/openapi.yaml
  horreum-backend/src/main/resources/application.properties
  horreum-web/package-lock.json
Labels: type/bug, branch/master, area/dependency, area/build

#1271 [0.11.x] Re-commit package-lock.json with the correct spacing. Fixes #1269
  horreum-backend/src/main/resources/application.properties
  horreum-web/package-lock.json
Labels: type/bug, area/UI, branch/0.11.x, area/dependency

#1273 Remove immutable dependency : Fixes #1272
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/master, area/UI, area/dependency, backport

#1274 [0.11.x] Remove immutable dependency : Fixes #1272
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/developer, area/UI, branch/0.11.x

#1276 Display datastore config to managers in Admin tab: Fixes #1275
  horreum-web/src/App.tsx
  horreum-web/src/auth.tsx
  horreum-web/src/domain/admin/Admin.tsx
Labels: type/bug, branch/master, area/UI, backport

#1277 [0.11.x] Display datastore config to managers in Admin tab: Fixes #1275
  horreum-web/src/App.tsx
  horreum-web/src/auth.tsx
  horreum-web/src/domain/admin/Admin.tsx
Labels: type/bug, area/UI, branch/0.11.x

#1279 [0.11.x] Bump vite-tsconfig-paths from 4.2.3 to 4.3.1 in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, branch/0.11.x, area/dependency

#1280 [0.11.x] Bump vite from 5.0.11 to 5.0.12 in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, branch/0.11.x, area/dependency

#1281 [0.11.x] Bump react-router from 6.21.3 to 6.22.0 in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, branch/0.11.x, area/dependency

#1212 Added TestExport to avoid creating unstructured json, fixes #860
  docs/site/content/en/docs/Tasks/import-export/import-export.png
  docs/site/content/en/docs/Tasks/import-export/index.md
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/ChangeDetection.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/Variable.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExperimentProfile.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Label.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Schema.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/SchemaExport.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Test.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/TestExport.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/Datastore.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/ExperimentProfileDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/LabelMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/VariableMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ActionServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/LogServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
  horreum-web/src/components/ExportImport.tsx
  horreum-web/src/components/ImportButton.tsx
  infra-legacy/example-data/quarkus_sb_test.json
Labels: type/bug, branch/master, area/backend

#1213 upgrade smallrye-openapi to 3.9
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/pom.xml
  horreum-web/src/api.tsx
  horreum-web/src/domain/runs/RunList.tsx
  horreum-web/src/domain/runs/TestDatasets.tsx
  horreum-web/src/domain/schemas/SchemaList.tsx
  horreum-web/src/domain/schemas/TestLabelModal.tsx
  horreum-web/src/domain/schemas/TryJsonPathModal.tsx
  horreum-web/src/domain/tests/AllTests.tsx
Labels: area/backend, area/dependency

#1300 fixes #1298 by avoiding redundant keycloak init
  horreum-web/src/keycloak.ts
Labels: type/bug, branch/master, area/UI, backport

#1299 Implement Basic Authentication for Elasticsearch datastore: Fixes #1295
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/BaseDatastoreConfig.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/Datastore.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/PostgresDatastore.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
  horreum-web/package-lock.json
  horreum-web/src/App.tsx
  horreum-web/src/domain/admin/Datastores.tsx
  horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
Labels: type/enhancement, branch/master, area/UI, area/backend, backport

#1288 Fix devservices with DB backup
  horreum-backend/src/main/resources/application.properties
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
Labels: type/enhancement, branch/master, area/developer, backport

#1303 [0.11.x] Fix devservices with DB backup
  horreum-backend/src/main/resources/application.properties
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/resources/KeycloakResource.java
Labels: type/bug, area/developer, branch/0.11.x

#1302 [0.11.x] Implement Basic Authentication for Elasticsearch datastore: Fixes #1295
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/BaseDatastoreConfig.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/Datastore.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/PostgresDatastore.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
  horreum-web/package-lock.json
  horreum-web/src/App.tsx
  horreum-web/src/domain/admin/Datastores.tsx
  horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
Labels: type/enhancement, area/UI, area/backend, branch/0.11.x

#1263 Changed default ordering to Decending and preserve ordering of DTOs.
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
Labels: area/UI, area/backend

#1282 Change `/labelValues` to match how the data is used
  docs/site/content/en/docs/Tutorials/grafana/index.md
  docs/site/content/en/docs/Tutorials/grafana/json_api_datasource.png
  docs/site/content/en/docs/Tutorials/grafana/json_api_panel_datasource.png
  docs/site/content/en/docs/Tutorials/grafana/json_api_panel_fields.png
  docs/site/content/en/docs/Tutorials/grafana/json_api_panel_filter.png
  docs/site/content/en/docs/Tutorials/grafana/json_api_panel_transform.png
  docs/site/content/en/docs/Tutorials/grafana/json_api_plugin.png
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/changes/Target.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ExportedLabelValues.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/TestMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
  horreum-web/src/domain/runs/TestDatasets.tsx
Labels: type/enhancement, branch/master, area/backend, priority/high, area/integration

#1227 Implementation of using BarValuesChart to display View Component values.
  horreum-web/src/domain/runs/DatasetComparison.tsx
Labels: area/UI

#1340 [0.11.x] Bump io.hypersistence:hypersistence-utils-hibernate-62 from 3.7.1 to 3.7.3
  horreum-backend/pom.xml
Labels: area/backend, area/dependency

#1342 Clear selected rows after Deletion of a row. fixes #957
  horreum-web/src/domain/runs/RunList.tsx
  horreum-web/src/domain/runs/components.tsx
Labels: area/UI

#1374 Remove System.out.println, fixes #1356
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
Labels: branch/master, area/backend, backport

#1373 [0.11.x] Bump @types/react-table from 7.7.14 to 7.7.19 in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/dependency

#1381 [0.11.x] Bump org.codehaus.mojo:exec-maven-plugin from 3.1.1 to 3.2.0
  pom.xml
Labels: area/dependency

#1383 remove ajv dependency: Fixes #1382
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/dependency, backport
