Repository Hyperfoil/Horreum, pull requests merged in 2024-03, with the labels that each got.

#1370 Add Report deletion task. fixes 974
  docs/site/content/en/docs/Concepts/core-concepts/index.md
  docs/site/content/en/docs/Tasks/manage-reports/confirm-report-deletion.png
  docs/site/content/en/docs/Tasks/manage-reports/index.md
  docs/site/content/en/docs/Tasks/manage-reports/report-configuration-list-view.png
  docs/site/content/en/docs/Tasks/manage-reports/total-reports-on-report-configuration-list-page.png
Labels: area/documentation

#1400 Fix docs
  docs/site/content/en/docs/Concepts/core-concepts/index.md
  docs/site/content/en/docs/Deployment/bare-metal.md
  docs/site/content/en/docs/Deployment/operator.md
  docs/site/content/en/docs/Tasks/add-users/index.md
  docs/site/content/en/docs/Tasks/configure-actions/index.md
  docs/site/content/en/docs/Tasks/configure-change-detection/index.md
  docs/site/content/en/docs/Tasks/create-new-test/index.md
  docs/site/content/en/docs/Tasks/define-schema-and-views/index.md
  docs/site/content/en/docs/Tasks/trasnform-runs-to-datasets/index.md
  docs/site/content/en/docs/Tasks/upload-run/index.md
  docs/site/content/en/docs/Tutorials/create-test-run/index.md
  docs/site/content/en/docs/Tutorials/get-started/index.md
Labels: area/documentation

#1429 Re-created package-lock.json
  horreum-web/package-lock.json
Labels: backport

#1437 Add configurable privacy statement link
  .gitignore
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ConfigService.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
  horreum-web/src/About.tsx
Labels: backport

#1440 Disable the privacy statement by default
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/ConfigServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumTestProfile.java
Labels: backport

#1422 Remove @NaturalId annotation from UserInfo: Fixes #1418
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/user/UserInfo.java
Labels: backport

#1431 [UI] fix selection of authentication mechanism
  horreum-web/src/auth.tsx
Labels: backport

#1432 Load all keycloak users on migration
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
Labels: area/backend, backport

#1451 upgrade to Quarkus 3.8.1, fixes #1244
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  pom.xml
Labels: area/backend, area/dependency, backport

#1450 Make UserService backend runtime configurable: Fixes #1445
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RolesAugmentor.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityMigration.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/UserBackEnd.java
  horreum-backend/src/main/resources/application.properties
Labels: backport

#1461 Fix test label calculation with all match
  .gitignore
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/Extractor.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/ExtractorDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExtractorMapper.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
  horreum-web/src/domain/schemas/JsonExtractor.tsx
  horreum-web/src/domain/schemas/Labels.tsx
  horreum-web/src/domain/schemas/Transformers.tsx
  infra-legacy/example-data/acme_transformer.json
  infra-legacy/example-data/quarkus_sb_schema.json
Labels: backport

#1397 Document Functions, Combination Function, Troubleshooting guide
  docs/site/content/en/docs/Concepts/core-concepts/index.md
  docs/site/content/en/docs/Reference/troubleshooting-functions/buttons-on-dataset-view.png
  docs/site/content/en/docs/Reference/troubleshooting-functions/effective-label-value.png
  docs/site/content/en/docs/Reference/troubleshooting-functions/index.md
  docs/site/content/en/docs/Reference/troubleshooting-functions/labels-calculation-log.png
  docs/site/content/en/docs/Reference/troubleshooting-functions/use-typeof-function.png
  docs/site/content/en/docs/Tasks/define-functions/index.md
  docs/site/content/en/docs/Tasks/define-schema-and-views/index.md
Labels: area/documentation, backport

#1465 fix grafana field jsonpath and add all fields
  docs/site/content/en/docs/Tutorials/grafana/json_api_panel_fields.png
Labels: area/documentation, backport

#1498 Remove general use of Elasticsearch dev service
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/ElasticsearchTestProfile.java
Labels: type/enhancement, area/developer, backport

#1497 fix #1486 and add Util unit tests
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UtilTest.java
Labels: backport

#1515 Bump @patternfly from 5.1.x to 5.2.x in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/dependency, backport

#1516 [0.12.x] Bump @patternfly from 5.1.x to 5.2.x in /horreum-web
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/dependency

#1525 Remove vertx dispatch and tiddy up UserServiceImpl
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/UserBackEnd.java
Labels: type/enhancement, area/backend, backport
