Repository Hyperfoil/Horreum, pull requests merged in 2024-06, with the labels that each got.

#1744 Import Test change detection variable fixes.
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/VariableMapper.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java
  horreum-backend/src/test/resources/data/acme_new_variable_test.json
  horreum-backend/src/test/resources/data/acme_sb_schema.json
Labels: type/bug, area/backend, backport

#1708 Create initial account when there are no accounts in the system
  horreum-backend/pom.xml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/SecurityBootstrap.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/KeycloakUserBackend.java
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/KeycloakUserServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/UserServiceAbstractTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumKeycloakTestResourceLifecycleManager.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/HorreumTestProfile.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/test/KeycloakTestProfile.java
  horreum-integration-tests/src/main/resources/application.properties
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/HorreumClientIT.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
Labels: backport

#1804 Add debug log to RoleManager
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RoleManager.java
Labels: backport

#1694 Sync `react` version with `react-dom`
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: type/enhancement, area/UI, area/dependency, backport

#1797 Change dataset filters to Patternfly Attribute Filter pattern: Fixes: #1346
  horreum-web/src/components/LabelFilter/FilterDropDown.tsx
  horreum-web/src/components/LabelFilter/LabelFilter.tsx
  horreum-web/src/components/LabelFilter/LabelFilterOption.tsx
  horreum-web/src/components/ToolbarLabelFilter.tsx
  horreum-web/src/domain/runs/TestDatasets.tsx
Labels: backport

#1832 Fix native typecast in queries
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/data/SchemaDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ChangesServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SqlServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasetServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/SchemaServiceTest.java
Labels: backport

#1854 Configure maven-jar-plugin to create a test classes jar.
  horreum-backend/pom.xml
Labels: backport, area/integration
