Repository Hyperfoil/Horreum, pull requests merged in 2024-01, with the labels that each got.

#1005 Chore: maven compiler 3.12.1
  pom.xml
Labels: enhancement

#1006 Bump quinoa.version - 2.3.1
  pom.xml
Labels: enhancement, stable

#1028 Extract plugin versions to maven properties
  horreum-backend/pom.xml
  horreum-client/pom.xml
  horreum-integration-tests/pom.xml
  pom.xml
Labels: enhancement, master, dependency

#1030 Unify json-schema-validator dependency version :
  horreum-backend/pom.xml
  pom.xml
Labels: enhancement, master, dependency

#1032 Resolve surefire-plugin.version from parent pom
  infra/horreum-dev-services/pom.xml
Labels: master, dependency

#1034 Do not fetch Test details for RecalculateDatasetsModal unless modal is open
  horreum-web/src/domain/tests/RecalculateDatasetsModal.tsx
Labels: bug, master, UI

#1054 Unify quarkus & plugin versions
  horreum-integration-tests/pom.xml
  pom.xml
Labels: enhancement, master

#1055 remove jandex-maven-plugin
  horreum-backend/pom.xml
Labels: enhancement, master

#1056 Bump keycloak from 22.0.4 to 23.0.3
  horreum-web/package-lock.json
  horreum-web/package.json
  pom.xml
Labels: dependency

#937 Remove db encryption with pgcrypto
  docs/site/content/en/docs/Deployment/bare-metal.md
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RoleManager.java
  horreum-backend/src/main/resources/application.properties
  horreum-backend/src/main/resources/db/changeLog.xml
  horreum-integration-tests/src/main/resources/application.properties
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/SelfSignedCert.java
Labels: enhancement, master, backend

#1064 Release Integration Test jars and push to sonatype staging : Fixes #897
  horreum-api/pom.xml
  horreum-client/pom.xml
  horreum-integration-tests/pom.xml
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
  pom.xml
Labels: enhancement, master

#1065 Release Integration Test jars and push to sonatype staging : Fixes #897
  horreum-api/pom.xml
  horreum-client/pom.xml
  horreum-integration-tests/pom.xml
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
  pom.xml
Labels: enhancement, stable

#1069 Add empty class to generate javadoc
  horreum-integration-tests/src/main/java/io/hyperfoil/tools/horreum/it/HorreumIntegrationTest.java
Labels: enhancement, stable

#1071 Revert releasing to staging - need to push file signatures
  pom.xml
Labels: bug, master, backend

#1072 Revert releasing to staging - need to push file signatures
  pom.xml
Labels: bug, stable

#1067 added more @Schema definitions to comply with the openapi-python-client, fixes #930
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/DatasetLog.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/alerting/TransformationLog.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/ActionLog.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/PersistentLog.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/ReportComponent.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/ReportLog.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/TableReport.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/report/TableReportConfig.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/ExperimentService.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/RunService.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/SchemaService.java
Labels: bug, master, backend

#1083 Update link in https://horreum.hyperfoil.io/docs/overview/, remove 'E…
  docs/site/content/en/docs/Overview/_index.md
Labels: documentation, master

#1085 change sql statements to text blocks
  docs/site/content/en/openapi/openapi.yaml
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ExperimentServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/NotificationServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ReportServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SubscriptionServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
Labels: enhancement, master, backend

#1090 Improve error message when creation of a new user fails
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
Labels: enhancement, master, backend

#1094 Upgrade nodejs and npm
  horreum-backend/src/main/resources/application.properties
Labels: enhancement, master

#1095 [backport] Upgrade nodejs and npm
  horreum-backend/src/main/resources/application.properties
Labels: enhancement, master

#1078 removed the before run update psql trigger, fixes #1058
  horreum-backend/src/main/resources/db/changeLog.xml
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/RunServiceTest.java
Labels: bug, master, backend

#1097 Backport of #1075
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java
Labels: branch/0.11.x

#1104 Create composite Manager role for new team. Fixes #970
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
Labels: type/bug, branch/master, area/backend

#1106 Backport of #1104
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java
Labels: branch/0.11.x

#1107 Backport of #1102
  pom.xml
Labels: branch/0.11.x

#1099 Backport of #1010
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/0.11.x

#1110 Backport of #1081
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/0.11.x

#1111 Backport of #1060
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/0.11.x

#1117 Backport of #1115
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/0.11.x

#1122 Configured button to be disabled when Experiments don't exist.
  horreum-web/src/domain/runs/DatasetData.tsx
Labels: area/UI

#1113 Added field name for Variable.
  horreum-web/src/domain/tests/Experiments.tsx
Labels: type/bug, area/UI

#1128 Backport of #1113
  horreum-web/src/domain/tests/Experiments.tsx
Labels: type/bug, area/UI, branch/0.11.x

#1129 Backport of #1061
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/stable, branch/0.11.x

#1119 Added suggestion to progress beyond current missing Run error.
  horreum-web/src/api.tsx
Labels: type/enhancement, branch/master, area/UI

#1131 Backport of #1119
  horreum-web/src/api.tsx
Labels: type/enhancement, branch/stable, area/UI, branch/0.11.x

#1112 Add documentation.
  docs/site/content/en/docs/Concepts/core-concepts/index.md
  docs/site/content/en/docs/Tasks/experiment-evaluation/dataset_list.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/dataset_selection.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/index.md
  docs/site/content/en/docs/Tasks/experiment-evaluation/individual_evaluation.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/multiple_dataset_comparison.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/select_for_comparison.png
Labels: area/documentation, type/enhancement, branch/master

#1132 Backport of #1112
  docs/site/content/en/docs/Concepts/core-concepts/index.md
  docs/site/content/en/docs/Tasks/experiment-evaluation/dataset_list.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/dataset_selection.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/index.md
  docs/site/content/en/docs/Tasks/experiment-evaluation/individual_evaluation.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/multiple_dataset_comparison.png
  docs/site/content/en/docs/Tasks/experiment-evaluation/select_for_comparison.png
Labels: area/documentation, type/enhancement, branch/stable, branch/0.11.x

#1138 Backport of #1134
  pom.xml
Labels: branch/0.11.x, area/dependency

#1139 Backport of #1135
  pom.xml
Labels: branch/0.11.x, area/dependency

#1140 Backport of #1136
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: branch/0.11.x, area/dependency

#1004 Migration react-router-dom 5 to 6
  horreum-web/package-lock.json
  horreum-web/package.json
  horreum-web/src/404.tsx
  horreum-web/src/App.tsx
  horreum-web/src/components/IndirectLink.tsx
  horreum-web/src/domain/alerting/Changes.tsx
  horreum-web/src/domain/reports/TableReportView.tsx
  horreum-web/src/domain/runs/DatasetComparison.tsx
  horreum-web/src/domain/runs/JsonPathSearchToolbar.tsx
  horreum-web/src/domain/schemas/Labels.tsx
  horreum-web/src/domain/schemas/Transformers.tsx
  horreum-web/src/domain/tests/ActionsUI.tsx
  horreum-web/src/domain/tests/ChangeDetectionForm.tsx
  horreum-web/src/index.tsx
Labels: type/enhancement, branch/master, area/UI, area/dependency, backport

#1142 [0.11.x] Migration react-router-dom 5 to 6
  horreum-web/package-lock.json
  horreum-web/package.json
  horreum-web/src/404.tsx
  horreum-web/src/App.tsx
  horreum-web/src/components/IndirectLink.tsx
  horreum-web/src/domain/alerting/Changes.tsx
  horreum-web/src/domain/reports/TableReportView.tsx
  horreum-web/src/domain/runs/DatasetComparison.tsx
  horreum-web/src/domain/runs/JsonPathSearchToolbar.tsx
  horreum-web/src/domain/schemas/Labels.tsx
  horreum-web/src/domain/schemas/Transformers.tsx
  horreum-web/src/domain/tests/ActionsUI.tsx
  horreum-web/src/domain/tests/ChangeDetectionForm.tsx
  horreum-web/src/index.tsx
Labels: branch/0.11.x, area/dependency

#1150 Revert "Compare fingerprints by hash"
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
Labels: type/bug, area/backend, priority/high, backport

#1151 Revert "Compare fingerprints by hash"
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
  horreum-backend/src/main/resources/db/changeLog.xml
Labels: type/bug, area/backend

#1152 [0.11.x] Revert "Compare fingerprints by hash"
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/entity/FingerprintDAO.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/AlertingServiceImpl.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/DatasetServiceImpl.java
Labels: type/bug, area/backend, branch/0.11.x

#1146 Fallback to Basic authentication when keycloak URL is not defined
  horreum-web/src/Login.tsx
  horreum-web/src/api.tsx
  horreum-web/src/auth.tsx
  horreum-web/src/keycloak.ts
Labels: type/enhancement, branch/master, area/backend

#1157 [0.11.x] Bump quarkus.version from 3.6.6 to 3.6.7
  pom.xml
Labels: branch/0.11.x, area/dependency

#1076 Migration CRA to VITE
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java
  horreum-web/index.html
  horreum-web/package-lock.json
  horreum-web/package.json
  horreum-web/src/index.tsx
  horreum-web/src/setupProxy.js
  horreum-web/tsconfig.json
  horreum-web/vite-env.d.ts
  horreum-web/vite.config.ts
Labels: type/enhancement, branch/master, area/UI, backport

#1158 [0.11.x] Migration CRA to VITE
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/RouteFilter.java
  horreum-web/index.html
  horreum-web/package-lock.json
  horreum-web/package.json
  horreum-web/src/index.tsx
  horreum-web/src/setupProxy.js
  horreum-web/tsconfig.json
  horreum-web/vite-env.d.ts
  horreum-web/vite.config.ts
Labels: type/enhancement, area/UI, branch/0.11.x

#1164 [0.11.x] Bump package-lock.json
  horreum-web/package-lock.json
Labels: area/UI

#1165 Reapply "Migration react-router-dom 5 to 6, fixes #723"
  horreum-web/package-lock.json
  horreum-web/package.json
  horreum-web/src/404.tsx
  horreum-web/src/App.tsx
  horreum-web/src/components/IndirectLink.tsx
  horreum-web/src/domain/alerting/Changes.tsx
  horreum-web/src/domain/reports/TableReportView.tsx
  horreum-web/src/domain/runs/DatasetComparison.tsx
  horreum-web/src/domain/runs/JsonPathSearchToolbar.tsx
  horreum-web/src/domain/schemas/Labels.tsx
  horreum-web/src/domain/schemas/Transformers.tsx
  horreum-web/src/domain/tests/ActionsUI.tsx
  horreum-web/src/domain/tests/ChangeDetectionForm.tsx
  horreum-web/src/index.tsx
Labels: type/bug, branch/master

#1166 Migrate useParams from react-router react-router-dom: Fixes #
  horreum-web/src/domain/reports/TableReportConfigPage.tsx
  horreum-web/src/domain/reports/TableReportPage.tsx
  horreum-web/src/domain/runs/Run.tsx
  horreum-web/src/domain/runs/TestDatasets.tsx
  horreum-web/src/domain/schemas/Schema.tsx
  horreum-web/src/domain/tests/Test.tsx
Labels: type/bug, branch/master, area/UI, backport

#1171 Dev Docs: backporting
  docs/RELEASE.md
Labels: area/documentation, type/enhancement

#1172 Docs: Add details of change detection algorithms: Fixes #889
  docs/site/content/en/docs/ChangeDetection/_index.md
  docs/site/content/en/docs/ChangeDetection/fixed-threshold/boundsChart.png
  docs/site/content/en/docs/ChangeDetection/fixed-threshold/configuration.png
  docs/site/content/en/docs/ChangeDetection/fixed-threshold/index.md
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/configuration.png
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/index.md
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/insufficientData.png
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/timeseries.png
  docs/site/content/en/docs/Deployment/_index.md
  docs/site/content/en/docs/Integrations/_index.md
  docs/site/content/en/docs/Reference/_index.md
  docs/site/content/en/docs/Tasks/_index.md
  docs/site/content/en/docs/Tasks/configure-change-detection/index.md
  docs/site/content/en/docs/Tasks/create-new-test/index.md
  docs/site/content/en/docs/Tasks/define-schema-and-views/index.md
Labels: area/documentation, type/enhancement, branch/master

#1173 [0.11.x] Docs: Add details of change detection algorithms: Fixes #889
  docs/site/content/en/docs/ChangeDetection/_index.md
  docs/site/content/en/docs/ChangeDetection/fixed-threshold/boundsChart.png
  docs/site/content/en/docs/ChangeDetection/fixed-threshold/configuration.png
  docs/site/content/en/docs/ChangeDetection/fixed-threshold/index.md
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/configuration.png
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/index.md
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/insufficientData.png
  docs/site/content/en/docs/ChangeDetection/relative-difference-of-means/timeseries.png
  docs/site/content/en/docs/Deployment/_index.md
  docs/site/content/en/docs/Integrations/_index.md
  docs/site/content/en/docs/Reference/_index.md
  docs/site/content/en/docs/Tasks/_index.md
  docs/site/content/en/docs/Tasks/configure-change-detection/index.md
  docs/site/content/en/docs/Tasks/create-new-test/index.md
  docs/site/content/en/docs/Tasks/define-schema-and-views/index.md
Labels: area/documentation, branch/0.11.x

#1170 Configure overflow setting to render a better UI.
  horreum-web/src/domain/runs/TestDatasets.tsx
Labels: type/bug, area/UI, backport

#1169 Use specific versions of node dependency
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, area/dependency, backport

#1174 [0.11.x] Configure overflow setting to render a better UI.
  horreum-web/src/domain/runs/TestDatasets.tsx
Labels: type/bug, area/UI, branch/0.11.x

#1175 [0.11.x] Use specific versions of node dependency
  horreum-web/package-lock.json
  horreum-web/package.json
Labels: area/UI, branch/0.11.x, area/dependency

#1178 [0.11.x] Fix dev service to start postgres only and allow horreum to start without oidc.auth-server-url
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/HorreumAuthorizationFilter.java
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
  horreum-integration-tests/src/test/java/io/hyperfoil/tools/horreum/it/ItResource.java
  infra/horreum-dev-services/deployment/src/main/java/io/hyperfoil/tools/horreum/dev/services/deployment/HorreumDevServicesProcessor.java
  infra/horreum-infra-common/src/main/java/io/hyperfoil/tools/horreum/infra/common/HorreumResources.java
Labels: type/enhancement, area/developer, branch/0.11.x

#1147 Detect when RLS has been a cause for error.
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-web/src/domain/runs/Run.tsx
Labels: type/bug, area/UI, backport

#1186 [0.11.x] Detect when RLS has been a cause for error.
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java
  horreum-web/src/domain/runs/Run.tsx
Labels: type/bug, area/UI, branch/0.11.x

#1185 [0.11.x] Bump quarkus.version from 3.6.7 to 3.6.8
  pom.xml
Labels: branch/0.11.x, area/dependency

#1189 Add Grafana documentation, fixed changes API for grafana integration: Fixes #490
  docs/site/content/en/docs/Integrations/grafana/create-dashboard.png
  docs/site/content/en/docs/Integrations/grafana/datasource_successful.png
  docs/site/content/en/docs/Integrations/grafana/define_metric.png
  docs/site/content/en/docs/Integrations/grafana/grafana_dashboard.png
  docs/site/content/en/docs/Integrations/grafana/grafana_install_json_plugin.png
  docs/site/content/en/docs/Integrations/grafana/horreum_datasource.png
  docs/site/content/en/docs/Integrations/grafana/index.md
  docs/site/content/en/docs/Integrations/grafana/panel_name.png
  docs/site/content/en/docs/Integrations/grafana/panel_save.png
  docs/site/content/en/docs/Integrations/grafana/plugin_add_new_datasource.png
  docs/site/content/en/docs/Integrations/grafana/setup-horreum-datasource.png
  docs/site/content/en/openapi/openapi.yaml
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/changes/Target.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/ChangesService.java
Labels: area/documentation, type/enhancement, branch/master, priority/high, backport

#1191 [0.11.x] Add Grafana documentation, fixed changes API for grafana integration: Fixes #490
  docs/site/content/en/docs/Integrations/grafana/create-dashboard.png
  docs/site/content/en/docs/Integrations/grafana/datasource_successful.png
  docs/site/content/en/docs/Integrations/grafana/define_metric.png
  docs/site/content/en/docs/Integrations/grafana/grafana_dashboard.png
  docs/site/content/en/docs/Integrations/grafana/grafana_install_json_plugin.png
  docs/site/content/en/docs/Integrations/grafana/horreum_datasource.png
  docs/site/content/en/docs/Integrations/grafana/index.md
  docs/site/content/en/docs/Integrations/grafana/panel_name.png
  docs/site/content/en/docs/Integrations/grafana/panel_save.png
  docs/site/content/en/docs/Integrations/grafana/plugin_add_new_datasource.png
  docs/site/content/en/docs/Integrations/grafana/setup-horreum-datasource.png
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/changes/Target.java
  horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/internal/services/ChangesService.java
Labels: area/documentation, type/enhancement, branch/0.11.x

#1201 Set base path for vite builds: Fixes #1176
  horreum-web/vite.config.ts
Labels: type/bug, branch/master, area/UI, backport

#1200 Migrate useParams from react-router react-router-dom for Runs: Fixes #1199
  horreum-web/package-lock.json
  horreum-web/src/domain/runs/RunList.tsx
Labels: type/bug, branch/master, area/UI, backport

#1202 [0.11.x] Set base path for vite builds: Fixes #1176
  horreum-web/vite.config.ts
Labels: type/bug, area/UI, branch/0.11.x

#1203 [0.11.x] Migrate useParams from react-router react-router-dom for Runs: Fixes #1199
  horreum-web/src/domain/runs/RunList.tsx
Labels: type/bug, area/UI, branch/0.11.x

#1205 [0.11.x] Vite CJS Node API deprecated
  horreum-web/package.json
Labels: type/bug, area/UI, branch/0.11.x, area/build

#1214 Upgrade react-router from v5 to v6. Fixes #1209
  horreum-web/package-lock.json
  horreum-web/package.json
  horreum-web/src/App.tsx
  horreum-web/src/components/FragmentTabs.tsx
  horreum-web/src/components/SaveChangesModal.tsx
  horreum-web/src/components/SavedTabs.tsx
  horreum-web/src/context/appContext.tsx
  horreum-web/src/domain/reports/TableReportConfigPage.tsx
  horreum-web/src/domain/tests/AllTests.tsx
  horreum-web/src/domain/tests/MissingDataNotifications.tsx
  horreum-web/src/domain/tests/Views.tsx
  horreum-web/src/index.tsx
Labels: type/bug, area/UI, priority/high, backport

#1228 [0.11.x] Change permissions on retreiving Datastores: Fixes #1204
  horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/BaseServiceTest.java
  horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/DatasourceTest.java
  horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx
Labels: type/bug, area/UI, area/backend, branch/0.11.x
